# Generated by Django 3.1.2 on 2020-10-14 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hq', '0002_auto_20201014_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='id_number',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
