# Generated by Django 3.1.2 on 2020-10-14 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hq', '0004_auto_20201014_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personimage',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hq.person'),
        ),
    ]
