# Generated by Django 3.1.2 on 2020-10-16 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hq', '0007_personimage_pictures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='id_number',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
