# Generated by Django 3.1.2 on 2020-10-29 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hq', '0008_auto_20201016_0846'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonBuffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=128, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
