# Generated by Django 3.1.2 on 2020-11-06 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reg_sign_in_out', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='user',
        ),
        migrations.DeleteModel(
            name='SignUp',
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
